export enum Actions {
  ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART',
  FETCH_CART_ITEMS = 'FETCH_CART_ITEMS',
  LOGIN = 'LOGIN',
  REGISTER = 'REGISTER',
  LOGOUT = 'LOGOUT',
  FETCH_CATEGORIES = 'FETCH_CATEGORIES'
}
